config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :home, only: :index
  resources :products, only: %i[new create]

  namespace :api, defaults: { format: :json } do
    resources :carts, only: %i[create show] do
      resources :cart_items, only: %i[create destroy]
    end
  end

  root to: "home#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  self.implicit_order_column = :created_at
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
end

app/models/cart_item.rb
# frozen_string_literal: true

class CartItem < ApplicationRecord
  validates :cart, :product, presence: true
  validates :quantity, numericality: { greater_than: 0 }

  belongs_to :cart, counter_cache: true
  belongs_to :product
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  validates :name, :price_cents, presence: true
  validates :price_cents, numericality: { greater_than: 0 }
  validates :rating,
            numericality: {
              greater_than_or_equal_to: 1,
              less_than_or_equal_to: 5,
            }, if: -> { rating.present? }

  has_one_attached :image
end

app/controllers/api/api_controller.rb
# frozen_string_literal: true

module Api
  class ApiController < ApplicationController
  end
end

app/controllers/api/cart_items_controller.rb
# frozen_string_literal: true

module Api
  class CartItemsController < ApiController
    def create
      @cart_item = CartItem.new(cart_item_params)

      if @cart_item.save
        render partial: "api/carts/cart",
               format: :json,
               status: :created,
               locals: { cart: @cart_item.cart }
      else
        render json: { errors: @cart_item.errors.full_messages },
               status: :unprocessable_entity
      end
    end

    def destroy
      @cart_item = CartItem.find_by(id: params[:id])

      if @cart_item&.destroy
        render partial: "api/carts/cart",
               format: :json,
               status: :ok,
               locals: { cart: @cart_item&.cart }
      else
        errors =
          if @cart_item.blank?
            ["Cart item not found."]
          else
            @cart_item.errors.full_messages
          end

        render json: { errors: errors }, status: :unprocessable_entity
      end
    end

    private

    def cart_item_params
      params
        .require(:cart_item)
        .permit(:cart_id, :quantity, :product_id)
    end
  end
end

app/controllers/api/carts_controller.rb
# frozen_string_literal: true

module Api
  class CartsController < ApiController
    def show
      @cart = Cart.find_by(id: params[:id])
      if @cart.present?
        render :show, format: :json
      else
        render json: { errors: ["Not found"] }, status: :not_found
      end
    end

    def create
      @cart = Cart.new

      if @cart.save
        render :show, format: :json, status: :created
      else
        render json: { errors: @cart.errors.full_messages },
               status: :unprocessable_entity
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @products =
      Product.all.order(created_at: :asc).decorate.as_json(
        only: %i[id name rating],
        methods: %i[price image_url star_url],
      )
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def new; end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash.now[:notice] = "Created: #{@product.name}"
    else
      flash.now[:alert] = @product.errors.full_messages.to_sentence
    end

    render :new
  end

  private

  def product_params
    attrs = params.require(:product).permit(:name, :rating, :price_cents, :image)
    attrs.merge(price_cents: attrs[:price_cents].to_f * 100)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  # TODO
  def default_product_image
    ""
  end
end

app/views/home/index.html.erb
<% content_for :head do %>
    <%= content_tag :script,
     raw(json_escape(@products.to_json)),
     id: "products" %>
<% end %>

<%= javascript_pack_tag "product_listing" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>storefront</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_pack_tag "application" %>

    <%= yield :head if content_for?(:head) %>
    <%= content_tag :div, nil, id: "cartsUrl", data: { carts_url: api_carts_url } %>
  </head>

  <body>
    <%= yield %>
    <div id="root"></div>
  </body>
</html>

app/views/products/new.html.erb
<h1> New Product </h1>

<% flash.each do |type, msg| %>
    <% if type == :alert %>
    <div class="alert alert-error">Errors: <%= msg %></div>
    <% else %>
    <div class="alert alert-info"><%= msg %></div>
    <% end %>
<% end %>

<%= form_with model: Product.new do |f| %>
    <div>
        <%= f.label :name, "Name" %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :price_cents, "Price (CAD)" %>
        <%= f.text_field :price_cents %>
    </div>

    <div>
        <%= f.label :rating, "Rating" %>
        <%= f.select :rating, (1..5).entries.unshift(nil) %>
    </div>


    <div>
        <%= f.label :image %>
        <%= f.file_field :image %>
    </div>

    <%= f.submit %>
<% end %>